//! Archived form of the catalog snapshot.
//!
//! The committed JSON snapshot (`data/catalog-snapshot.json`) stays the source
//! of truth: it is what the `snapshot` subcommand emits, what drift review
//! diffs line by line, and what `--snapshot PATH` accepts. This module defines
//! the *derived* form the binary embeds instead of that JSON: an rkyv archive
//! whose hot fields (service ids, tool names, descriptions) are readable in
//! place after one checked validation, and whose input/output schemas -- 60%
//! of the snapshot, read only by `describe_tools` -- are held as per-tool
//! zstd frames that stay compressed until something asks.
//!
//! # Trust boundary
//!
//! Only the embedded archive, generated by `snapshot --from` out of the
//! committed JSON and pinned to it by a unit test, is ever read by this
//! module in production. Operator-supplied `--snapshot PATH` files remain
//! JSON and go through serde as before, so untrusted bytes never reach rkyv
//! at all. Access is checked ([`rkyv::access`], `bytecheck`) even for the
//! embedded copy: a corrupted or stale artifact must fail with a clean error,
//! never undefined behaviour.

use rkyv::{Archive, Serialize as RkyvSerialize, rancor};

use crate::catalog::{CatalogSource, Snapshot};

/// First bytes of an archive file; `file` recognizes it, humans grep it.
pub const ARCHIVE_MAGIC: [u8; 4] = *b"MGSA";

/// Bump on any change to the archived layout below.
///
/// The header is read before rkyv sees a byte, so an old binary refuses a new
/// archive (and vice versa) with a version message instead of a validation
/// failure deep inside rkyv.
pub const ARCHIVE_FORMAT_VERSION: u32 = 1;

/// Header length; also the alignment the rkyv payload is placed at.
///
/// 16 bytes keeps the payload at the alignment `include_bytes!` embedding
/// provides (the embedding site wraps the bytes in a 16-aligned type), so the
/// checked access never fails on alignment for a well-formed file.
pub const ARCHIVE_HEADER_LEN: usize = 16;

/// zstd level for schema frames.
///
/// Chosen for size: compression happens only when a snapshot is regenerated,
/// decompression speed at this level is no worse than at low levels, and the
/// frames are embedded in the shipped binary where every KB is permanent.
const SCHEMA_ZSTD_LEVEL: i32 = 19;

/// Failures building, reading, or verifying an archive.
#[derive(Debug, thiserror::Error)]
pub enum ArchiveError {
    /// The bytes end before the header does.
    #[error("catalog archive is {len} bytes, shorter than its {ARCHIVE_HEADER_LEN}-byte header")]
    TooShort {
        /// How many bytes there were.
        len: usize,
    },

    /// The bytes do not start with [`ARCHIVE_MAGIC`].
    #[error("catalog archive does not start with the `MGSA` magic; not an archive")]
    BadMagic,

    /// The archive was written by a different format version.
    #[error(
        "catalog archive is format version {found}, this binary reads {ARCHIVE_FORMAT_VERSION}; \
         regenerate it with `snapshot --from data/catalog-snapshot.json`"
    )]
    UnsupportedVersion {
        /// Version the file claims.
        found: u32,
    },

    /// The rkyv payload failed checked validation.
    #[error("catalog archive payload failed validation; the artifact is corrupt or stale")]
    Invalid(#[source] rancor::Error),

    /// A schema could not be serialized while building the archive.
    #[error("schema of `{tool}` could not be serialized")]
    SchemaSerialize {
        /// Namespaced tool name.
        tool: String,
        /// Underlying cause.
        #[source]
        source: serde_json::Error,
    },

    /// A schema frame could not be compressed while building the archive.
    #[error("schema of `{tool}` could not be compressed")]
    SchemaCompress {
        /// Namespaced tool name.
        tool: String,
        /// Underlying cause.
        #[source]
        source: std::io::Error,
    },

    /// Tool annotations could not be serialized while building the archive.
    #[error("annotations of `{tool}` could not be serialized")]
    AnnotationsSerialize {
        /// Namespaced tool name.
        tool: String,
        /// Underlying cause.
        #[source]
        source: serde_json::Error,
    },

    /// A tool disagreed with its service about the service id.
    #[error("tool `{tool}` claims service `{claimed}` but is listed under `{actual}`")]
    ServiceMismatch {
        /// Namespaced tool name.
        tool: String,
        /// The tool's own `service_id` field.
        claimed: String,
        /// The service it is listed under.
        actual: String,
    },

    /// The rkyv serializer itself failed.
    #[error("catalog archive could not be serialized")]
    Serialize(#[source] rancor::Error),
}

/// Root of the archived snapshot.
#[derive(Archive, RkyvSerialize)]
#[rkyv(derive(Debug))]
pub struct SnapshotArchive {
    /// RFC 3339 timestamp copied from the source snapshot.
    pub generated_at: String,
    /// Per-service catalogs, in the source snapshot's (sorted) order.
    pub services: Vec<ServiceEntry>,
}

/// One service's tools.
#[derive(Archive, RkyvSerialize)]
#[rkyv(derive(Debug))]
pub struct ServiceEntry {
    /// Registry service id (e.g. `run`); each tool's prefix and `service_id`.
    pub service_id: String,
    /// Whether the source snapshot recorded these tools as live-fetched.
    pub live: bool,
    /// The service's tools, in the source snapshot's (sorted) order.
    pub tools: Vec<ToolEntry>,
}

/// One tool, hot fields in place and schemas as compressed frames.
#[derive(Archive, RkyvSerialize)]
#[rkyv(derive(Debug))]
pub struct ToolEntry {
    /// `{service}__{tool}`, globally unique.
    pub namespaced_name: String,
    /// Upstream tool name.
    pub name: String,
    /// Description text; `None` when the upstream sent none.
    pub description: Option<String>,
    /// `annotations` as compact JSON; tiny, parsed only where needed.
    pub annotations_json: Option<String>,
    /// zstd frame of the input schema's compact JSON.
    pub input_schema_zstd: Vec<u8>,
    /// Decompressed length of `input_schema_zstd`.
    pub input_schema_len: u32,
    /// zstd frame of the output schema's compact JSON, when the tool has one.
    pub output_schema_zstd: Option<Vec<u8>>,
    /// Decompressed length of `output_schema_zstd`.
    pub output_schema_len: u32,
}

/// Serialize `snapshot` into a complete archive file: header plus payload.
///
/// # Errors
///
/// Any [`ArchiveError`] variant except the read-side ones; in particular
/// [`ArchiveError::ServiceMismatch`] if a tool's recorded `service_id`
/// disagrees with the service it is listed under, which would make the
/// archive's once-per-service id wrong for that tool.
pub fn build(snapshot: &Snapshot) -> Result<Vec<u8>, ArchiveError> {
    let mut services = Vec::with_capacity(snapshot.services.len());
    for service in &snapshot.services {
        let mut tools = Vec::with_capacity(service.tools.len());
        for tool in &service.tools {
            if tool.service_id != service.service_id {
                return Err(ArchiveError::ServiceMismatch {
                    tool: tool.namespaced_name.clone(),
                    claimed: tool.service_id.clone(),
                    actual: service.service_id.clone(),
                });
            }
            let (input_schema_zstd, input_schema_len) =
                compress_schema(&tool.namespaced_name, &tool.tool.input_schema)?;
            let (output_schema_zstd, output_schema_len) = match tool.tool.output_schema.as_deref() {
                Some(schema) => {
                    let (frame, len) = compress_schema(&tool.namespaced_name, schema)?;
                    (Some(frame), len)
                }
                None => (None, 0),
            };
            let annotations_json = match &tool.tool.annotations {
                Some(annotations) => {
                    Some(serde_json::to_string(annotations).map_err(|source| {
                        ArchiveError::AnnotationsSerialize {
                            tool: tool.namespaced_name.clone(),
                            source,
                        }
                    })?)
                }
                None => None,
            };
            tools.push(ToolEntry {
                namespaced_name: tool.namespaced_name.clone(),
                name: tool.tool.name.to_string(),
                description: tool.tool.description.as_deref().map(str::to_owned),
                annotations_json,
                input_schema_zstd,
                input_schema_len,
                output_schema_zstd,
                output_schema_len,
            });
        }
        services.push(ServiceEntry {
            service_id: service.service_id.clone(),
            live: service.source == CatalogSource::Live,
            tools,
        });
    }

    let archive = SnapshotArchive {
        generated_at: snapshot.generated_at.clone(),
        services,
    };
    let payload = rkyv::to_bytes::<rancor::Error>(&archive).map_err(ArchiveError::Serialize)?;

    let mut bytes = Vec::with_capacity(ARCHIVE_HEADER_LEN + payload.len());
    bytes.extend_from_slice(&ARCHIVE_MAGIC);
    bytes.extend_from_slice(&ARCHIVE_FORMAT_VERSION.to_le_bytes());
    bytes.extend_from_slice(&[0u8; ARCHIVE_HEADER_LEN - 8]);
    bytes.extend_from_slice(&payload);
    Ok(bytes)
}

/// Compress one schema object to a zstd frame plus its decompressed length.
///
/// Frames carry zstd's content checksum: rkyv's validation sees a frame only
/// as bytes, so the checksum is what turns a flipped bit inside one into a
/// clean decompression error instead of silently different JSON.
fn compress_schema(
    tool: &str,
    schema: &rmcp::model::JsonObject,
) -> Result<(Vec<u8>, u32), ArchiveError> {
    let compress = |json: &[u8]| -> std::io::Result<Vec<u8>> {
        let mut compressor = zstd::bulk::Compressor::new(SCHEMA_ZSTD_LEVEL)?;
        compressor.set_parameter(zstd::zstd_safe::CParameter::ChecksumFlag(true))?;
        compressor.compress(json)
    };

    let json = serde_json::to_vec(schema).map_err(|source| ArchiveError::SchemaSerialize {
        tool: tool.to_owned(),
        source,
    })?;
    let frame = compress(&json).map_err(|source| ArchiveError::SchemaCompress {
        tool: tool.to_owned(),
        source,
    })?;
    let len = u32::try_from(json.len()).expect("a schema document is far smaller than 4 GiB");
    Ok((frame, len))
}

/// Validate `bytes` as an archive file and return its archived view.
///
/// Checked access on purpose, even though production only ever passes the
/// embedded artifact: the cost is one validation pass at startup, and what it
/// buys is that a corrupt or stale artifact -- or a future refactor that
/// feeds this function something else -- fails with [`ArchiveError`] instead
/// of undefined behaviour.
///
/// # Errors
///
/// [`ArchiveError::TooShort`], [`ArchiveError::BadMagic`] or
/// [`ArchiveError::UnsupportedVersion`] from the header;
/// [`ArchiveError::Invalid`] when the rkyv payload fails validation,
/// including misaligned input.
pub fn access(bytes: &[u8]) -> Result<&ArchivedSnapshotArchive, ArchiveError> {
    if bytes.len() < ARCHIVE_HEADER_LEN {
        return Err(ArchiveError::TooShort { len: bytes.len() });
    }
    if bytes[..4] != ARCHIVE_MAGIC {
        return Err(ArchiveError::BadMagic);
    }
    let found = u32::from_le_bytes(bytes[4..8].try_into().expect("slice of length 4"));
    if found != ARCHIVE_FORMAT_VERSION {
        return Err(ArchiveError::UnsupportedVersion { found });
    }
    rkyv::access::<ArchivedSnapshotArchive, rancor::Error>(&bytes[ARCHIVE_HEADER_LEN..])
        .map_err(ArchiveError::Invalid)
}

/// Decompress one schema frame back to its compact JSON bytes.
///
/// # Errors
///
/// The underlying zstd error; the caller decides how loud to be, since the
/// embedded frames were verified at generation and a failure here means the
/// artifact and the identity test have diverged from the binary.
pub fn decompress_schema(frame: &[u8], raw_len: u32) -> std::io::Result<Vec<u8>> {
    zstd::bulk::decompress(frame, raw_len as usize)
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use serde_json::json;

    use super::*;
    use crate::catalog::{Catalog, NamespacedTool, ServiceCatalog};

    /// Build a `Tool` through serde; `rmcp::model::Tool` is `#[non_exhaustive]`.
    fn tool(name: &str, description: &str, with_output: bool) -> rmcp::model::Tool {
        let mut value = json!({
            "name": name,
            "description": description,
            "inputSchema": { "type": "object", "properties": { "p": { "type": "string" } } },
            "annotations": { "readOnlyHint": true },
        });
        if with_output {
            value["outputSchema"] = json!({ "type": "object", "properties": {} });
        }
        serde_json::from_value(value).expect("test tool literal is valid")
    }

    fn sample_snapshot() -> Snapshot {
        let services = vec![
            ServiceCatalog {
                service_id: "bigquery".to_owned(),
                source: CatalogSource::Snapshot,
                tools: vec![NamespacedTool::new(
                    "bigquery",
                    tool("list_datasets", "List BigQuery datasets", false),
                )],
            },
            ServiceCatalog {
                service_id: "run".to_owned(),
                source: CatalogSource::Live,
                tools: vec![
                    NamespacedTool::new(
                        "run",
                        tool("get_service", "Get one Cloud Run service", true),
                    ),
                    NamespacedTool::new(
                        "run",
                        tool("list_services", "List Cloud Run services", false),
                    ),
                ],
            },
        ];
        Catalog::new(services)
            .expect("sample satisfies namespacing invariants")
            .to_snapshot("2026-08-20T00:00:00Z".to_owned())
    }

    #[test]
    fn an_archive_round_trips_every_field() {
        let snapshot = sample_snapshot();
        let bytes = build(&snapshot).expect("sample archives");
        let archived = access(&bytes).expect("a freshly built archive validates");

        assert_eq!(archived.generated_at.as_str(), snapshot.generated_at);
        assert_eq!(archived.services.len(), snapshot.services.len());
        for (archived_service, service) in archived.services.iter().zip(&snapshot.services) {
            assert_eq!(archived_service.service_id.as_str(), service.service_id);
            assert_eq!(archived_service.live, service.source == CatalogSource::Live);
            assert_eq!(archived_service.tools.len(), service.tools.len());
            for (archived_tool, tool) in archived_service.tools.iter().zip(&service.tools) {
                assert_eq!(archived_tool.namespaced_name.as_str(), tool.namespaced_name);
                assert_eq!(archived_tool.name.as_str(), &*tool.tool.name);
                assert_eq!(
                    archived_tool.description.as_deref(),
                    tool.tool.description.as_deref()
                );

                let input = decompress_schema(
                    archived_tool.input_schema_zstd.as_slice(),
                    archived_tool.input_schema_len.to_native(),
                )
                .expect("input frame inflates");
                let input: serde_json::Value =
                    serde_json::from_slice(&input).expect("input frame is JSON");
                assert_eq!(input, json!(&*tool.tool.input_schema));

                match (
                    &archived_tool.output_schema_zstd,
                    tool.tool.output_schema.as_deref(),
                ) {
                    (rkyv::option::ArchivedOption::Some(frame), Some(schema)) => {
                        let output = decompress_schema(
                            frame.as_slice(),
                            archived_tool.output_schema_len.to_native(),
                        )
                        .expect("output frame inflates");
                        let output: serde_json::Value =
                            serde_json::from_slice(&output).expect("output frame is JSON");
                        assert_eq!(output, json!(schema));
                    }
                    (rkyv::option::ArchivedOption::None, None) => {}
                    (frame, schema) => panic!(
                        "output schema presence diverged: archived {:?}, source {:?}",
                        frame.is_some(),
                        schema.is_some()
                    ),
                }
            }
        }
    }

    #[test]
    fn header_failures_are_clean_and_specific() {
        let bytes = build(&sample_snapshot()).expect("sample archives");

        type Expected = fn(&ArchiveError) -> bool;
        let tests: HashMap<&str, (Vec<u8>, Expected)> = HashMap::from([
            (
                "error: shorter than the header",
                (
                    bytes[..8].to_vec(),
                    (|e| matches!(e, ArchiveError::TooShort { len: 8 })) as Expected,
                ),
            ),
            (
                "error: wrong magic",
                (
                    {
                        let mut corrupt = bytes.clone();
                        corrupt[0] = b'X';
                        corrupt
                    },
                    |e| matches!(e, ArchiveError::BadMagic),
                ),
            ),
            (
                "error: future format version",
                (
                    {
                        let mut future = bytes.clone();
                        future[4..8].copy_from_slice(&(ARCHIVE_FORMAT_VERSION + 1).to_le_bytes());
                        future
                    },
                    |e| matches!(e, ArchiveError::UnsupportedVersion { found } if *found == ARCHIVE_FORMAT_VERSION + 1),
                ),
            ),
        ]);
        for (name, (input, matches_expected)) in tests {
            let error = access(&input).expect_err(name);
            assert!(matches_expected(&error), "{name}: got {error}");
        }
    }

    #[test]
    fn a_corrupted_payload_is_a_clean_error_not_a_panic() {
        let bytes = build(&sample_snapshot()).expect("sample archives");

        // Flip a byte at every offset of the payload. Validation guards
        // structure, not content: a flip inside a string or a compressed
        // frame can leave a structurally valid archive, but every flip must
        // come back as `Ok` or as `Invalid` -- never a panic, never another
        // error class.
        let mut rejected = 0usize;
        for at in ARCHIVE_HEADER_LEN..bytes.len() {
            let mut corrupt = bytes.clone();
            corrupt[at] ^= 0xA5;
            match access(&corrupt) {
                Ok(_) => {}
                Err(ArchiveError::Invalid(_)) => rejected += 1,
                Err(other) => panic!("offset {at}: unexpected error class {other}"),
            }
        }
        assert!(rejected > 0, "no corruption was caught structurally");

        // The root descriptor lives at the end of an rkyv payload; smashing
        // the tail must always be a structural catch.
        let mut smashed = bytes.clone();
        let tail = smashed.len() - 4;
        smashed[tail..].fill(0xFF);
        assert!(
            matches!(access(&smashed), Err(ArchiveError::Invalid(_))),
            "a smashed root descriptor must fail validation"
        );
    }

    /// A flip inside a schema frame validates structurally -- the frame is
    /// opaque bytes to rkyv -- and must instead die cleanly in zstd, whose
    /// content checksum every frame carries.
    #[test]
    fn a_corrupted_schema_frame_fails_at_decompression_not_silently() {
        let snapshot = sample_snapshot();
        let bytes = build(&snapshot).expect("sample archives");
        let archived = access(&bytes).expect("fresh archive validates");

        let frame = archived.services[0].tools[0].input_schema_zstd.as_slice();
        let raw_len = archived.services[0].tools[0].input_schema_len.to_native();
        assert!(frame.len() >= 12, "sanity: a frame has header + checksum");

        // Locate the frame inside the file and flip a byte in its middle.
        let at = bytes
            .windows(frame.len())
            .position(|window| window == frame)
            .expect("the frame's bytes occur in the file");
        let mut corrupt = bytes.clone();
        corrupt[at + frame.len() / 2] ^= 0xA5;

        let archived = match access(&corrupt) {
            Ok(archived) => archived,
            // If the flip happened to break structure anyway, the clean
            // error already proves the property this test is after.
            Err(ArchiveError::Invalid(_)) => return,
            Err(other) => panic!("unexpected error class {other}"),
        };
        let corrupted_frame = archived.services[0].tools[0].input_schema_zstd.as_slice();
        decompress_schema(corrupted_frame, raw_len)
            .expect_err("a corrupted frame must fail its checksum, not yield different JSON");
    }

    #[test]
    fn misaligned_input_is_rejected_not_undefined() {
        let bytes = build(&sample_snapshot()).expect("sample archives");
        // Shift the whole file by one byte inside a bigger buffer, so the
        // payload loses the alignment the header guarantees.
        let mut shifted = vec![0u8; bytes.len() + 1];
        shifted[1..].copy_from_slice(&bytes);
        let error = access(&shifted[1..]).expect_err("misaligned payload must not validate");
        assert!(
            matches!(error, ArchiveError::Invalid(_) | ArchiveError::BadMagic),
            "got {error}"
        );
    }

    #[test]
    fn a_tool_that_disagrees_with_its_service_fails_the_build() {
        let mut snapshot = sample_snapshot();
        snapshot.services[0].tools[0].service_id = "someoneelse".to_owned();
        let error = build(&snapshot).expect_err("mismatched service ids must not archive");
        assert!(
            matches!(error, ArchiveError::ServiceMismatch { ref claimed, .. } if claimed == "someoneelse"),
            "got {error}"
        );
    }

    /// The derived artifact next to the committed JSON must describe exactly
    /// the same catalog. This is what lets the archive be a build input while
    /// the JSON stays the reviewed source of truth: any skew fails the suite,
    /// so it cannot land.
    #[test]
    fn committed_archive_matches_the_committed_json() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let json = std::fs::read_to_string(root.join("data/catalog-snapshot.json"))
            .expect("committed JSON snapshot exists");
        let snapshot: Snapshot = serde_json::from_str(&json).expect("committed snapshot parses");

        let committed = std::fs::read(root.join("data/catalog-snapshot.bin")).expect(
            "committed archive exists; regenerate with \
             `snapshot --from data/catalog-snapshot.json --out data/catalog-snapshot.json`",
        );
        let rebuilt = build(&snapshot).expect("committed snapshot archives");
        assert_eq!(
            committed, rebuilt,
            "data/catalog-snapshot.bin has drifted from data/catalog-snapshot.json; \
             regenerate it and commit both together"
        );
        access(&committed).expect("the committed archive validates");
    }
}
